# Generated by Django 3.2.15 on 2023-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230514_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, help_text='Id товара на stripe.', max_length=128, null=True),
        ),
    ]
